version: '3.8'

services:
  evolution_api:
    image: atendare/evolution-api:latest
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./evolution.env
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution_net

  redis:
    image: redis:latest
    container_name: evolution_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - evolution_net

networks:
  evolution_net:
    driver: bridge

volumes:
  evolution_instances:
